USE DBRDVMEDECINS

CREATE TABLE MEDECINS(
ID BIGINT IDENTITY PRIMARY KEY,
TITRE VARCHAR(50),
NOM VARCHAR(50),
PRENOM VARCHAR(50))

CREATE TABLE CLIENTS(
ID BIGINT IDENTITY PRIMARY KEY,
TITRE VARCHAR(50),
NOM VARCHAR(50),
PRENOM VARCHAR(50))

CREATE TABLE CRENEAUX(
ID BIGINT IDENTITY PRIMARY KEY,
HDEBUT INT,
MDEBUT INT,
HFIN INT,
MFIN INT,
ID_MEDECIN BIGINT FOREIGN KEY REFERENCES dbo.MEDECINS(ID))

CREATE TABLE RV(
ID BIGINT IDENTITY PRIMARY KEY,
JOUR DATE,
ID_CLIENT BIGINT FOREIGN KEY REFERENCES dbo.CLIENTS(ID),
ID_CRENEAU BIGINT FOREIGN KEY REFERENCES dbo.CRENEAUX(ID))

ALTER TABLE RV ADD CONSTRAINT UNQ1_RV UNIQUE (JOUR, ID_CRENEAU);